export const houseBuild = [
  "Micro Home",
  "Tiny Home",
  "Small Home",
  "Regular Home",
];

export const houseConcept = ["Open Concept", "Closed Concept"];

export const houseStyle = [
  "Cape Cod",
  "Contemporary",
  "Shotgun",
  "Midcentury",
  "Cottage",
  "Trailer",
  "Container",
  "Colonial",
  "Craftsman",
  "Ranch",
  "Art Deco",
  "Underground",
  "Bungalow",
  "Abandoned",
  "Rustic",
  "Farmhouse",
  "Suburban",
  "Dealers Choice",
  "roll2",
];

export const houseExterior = [
  "Brick",
  "Panelling",
  "Siding",
  "Shingles",
  "Metal",
  "Dealers Choice",
  "roll2",
  "roll3",
];

export const exteriorColorScheme = [
  "Boring Beige",
  "Neon",
  "Earthy",
  "Beachy",
  "Pastel",
  "Jewel Tones",
  "Monochromatic",
  "Primary Colors",
  "Neutral with pop of color",
  "Bold",
  "High Contrast",
  "Dealer's Choice",
];

export const interiorColorScheme = [
  "Boring Beige",
  "Neon",
  "Earthy",
  "Beachy",
  "Pastel",
  "Jewel Tones",
  "Monochromatic",
  "Primary Colors",
  "Neutral with pop of color",
  "Bold",
  "High Contrast",
  "Dealer's Choice",
];

export const exteriorFeatures = [
  "Pond",
  "Garden",
  "Pool",
  "Sandbox",
  "Patio",
  "Porch",
  "Driveway",
  "Hottub",
  "Fire Pit",
  "Livestock",
  "swingset",
  "shed",
  "monkey bars",
  "garage",
  "water feature",
  "chimney",
  "Get Wet (Splash pad, sprinklers, waterballoons)",
  "Crafting Space (juices, Candles)",
  "Picinic Area",
  "Dealer's Choice",
];

export const extraRoom = [
  "Storage room",
  "basement",
  "attic",
  "gym",
  "art studio",
  "nursery",
  "game room",
  "guestroom",
  "crafting room",
  "greenhouse",
  "library",
  "laundry room",
  "meditation space",
  "Storage room",
  "work shop",
  "music room",
  "playroom",
  "office",
  "Dealer's Choice",
  "roll2",
];

export const interiorFeatures = [
  "Light Switches",
  "Pet door",
  "mother in law door",
  "window planter boxes",
  "fireplace",
  "built in shelving",
  "carpeted bedrooms",
  "radiators",
  "ceiling fans",
  "thermostats",
  "overhead lighting",
  "Dealer's Choice",
];

export const familyType = ["Family", "Single Sim", "Couple", "Roommates"];

export const chaos = [
  "Jail Cell",
  "toilet cult shrine",
  "cupcake machine",
  "make it grungy",
  "too many plants",
  "too much clutter",
  "messy sims",
  "cemetry/urns",
  "electricity is the devil",
  "tragic clown painting",
  "grogu arrives",
  "mooder gauntlet",
  "Suit of Armour",
  "open air bathroom",
  "chairs are toilets",
  "braking bad",
  "phone a friend",
  "leave it alone",
  "roll2",
];
