export const expansionPackList = [
    "Get to Work",
    "Get Together",
    "City Living",
    "Cats & Dogs",
    "Seasons",
    "Get Famous",
    "Island Living",
    "Discover University",
    "Eco Lifestyle",
    "Snowy Escape",
    "Cottage Living",
    "High School Years",
    "Growing Together",
];

export const gamePackList = [
    "Outdoor Retreat",
    "Spa Day",
    "Dine Out",
    "Vampires",
    "Parenthood",
    "Jungle Adventure",
    "StrangerVille",
    "Realm of Magic",
    "Journey to Batuu",
    "Dream Home Decorator",
    "My Wedding Stories",
    "Werewolves",
];

export const stuffPackList = [
    "Luxury Party",
    "Perfect Patio",
    "Cool Kitchen",
    "Spooky Stuff",
    "Movie Hangout",
    "Romantic Garden",
    "Kids Room",
    "Backyard",
    "Vintage Glamour",
    "Bowling Night",
    "Fitness",
    "Toddler",
    "Laundry Day",
    "My First Pet",
    "Moschino",
    "Tiny Living",
    "Nifty Knitting",
    "Paranormal",
];

export const kitsList = [
    "Country Kitchen",
    "Bust the Dust",
    "Throwback Fit",
    "Courtyard Oasis",
    "Industrial Loft",
    "Fashion Street",
    "Incheon Arrivals",
    "Blooming Rooms",
    "Mondern Menswear",
    "Carnaval Streetwear",
    "Décor to the Max",
    "Little Campers",
    "Moonlight Chich",
    "First Fits",
    "Desert Luxe",
    "Everyday Clutter",
    "Pastel Pop",
    "Bathroom Clutter",
    "Simtimates Collection",
    "Basement Treasures",
    "Greenhouse Haven",
    "Book Nook",
    "Grunge Revival",
];

export const houseBuild = [
  { value: "Micro Home", pack: "base" },
  { value: "Tiny Home", pack: "base" },
  { value: "Small Home", pack: "base" },
  { value: "Regular Home", pack: "base" },
];

export const houseConcept = [
  { value: "Open Concept", pack: "base" },
  { value: "Closed Concept", pack: "base" },
];

export const houseStyle = [
  { value: "Cape Cod", pack: "base" },
  { value: "Contemporary", pack: "base" },
  { value: "Shotgun", pack: "base" },
  { value: "Midcentury", pack: "base" },
  { value: "Cottage", pack: "base" },
  { value: "Trailer", pack: "base" },
  { value: "Container", pack: "base" },
  { value: "Colonial", pack: "base" },
  { value: "Craftsman", pack: "base" },
  { value: "Ranch", pack: "base" },
  { value: "Art Deco", pack: "base" },
  { value: "Underground", pack: "base" },
  { value: "Bungalow", pack: "base" },
  { value: "Abandoned", pack: "base" },
  { value: "Rustic", pack: "base" },
  { value: "Farmhouse", pack: "base" },
  { value: "Suburban", pack: "base" },
  { value: "Dealers Choice", pack: "base" },
  { value: "roll2", pack: "base" },
];

export const houseExterior = [
  { value: "Brick", pack: "base" },
  { value: "Panelling", pack: "base" },
  { value: "Siding", pack: "base" },
  { value: "Shingles", pack: "base" },
  { value: "Metal", pack: "base" },
  { value: "Dealers Choice", pack: "base" },
  { value: "roll2", pack: "base" },
  { value: "roll3", pack: "base" },
];

export const exteriorColorScheme = [
  { value: "Boring Beige", pack: "base" },
  { value: "Neon", pack: "base" },
  { value: "Earthy", pack: "base" },
  { value: "Beachy", pack: "base" },
  { value: "Pastel", pack: "base" },
  { value: "Jewel Tones", pack: "base" },
  { value: "Monochromatic", pack: "base" },
  { value: "Primary Colors", pack: "base" },
  { value: "Neutral with pop of color", pack: "base" },
  { value: "Bold", pack: "base" },
  { value: "High Contrast", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
];

export const interiorColorScheme = [
  { value: "Boring Beige", pack: "base" },
  { value: "Neon", pack: "base" },
  { value: "Earthy", pack: "base" },
  { value: "Beachy", pack: "base" },
  { value: "Pastel", pack: "base" },
  { value: "Jewel Tones", pack: "base" },
  { value: "Monochromatic", pack: "base" },
  { value: "Primary Colors", pack: "base" },
  { value: "Neutral with pop of color", pack: "base" },
  { value: "Bold", pack: "base" },
  { value: "High Contrast", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
];

export const exteriorFeatures = [
  { value: "Pond", pack: "base" },
  { value: "Garden", pack: "base" },
  { value: "Pool", pack: "base" },
  { value: "Sandbox", pack: "base" },
  { value: "Patio", pack: "base" },
  { value: "Porch", pack: "base" },
  { value: "Driveway", pack: "base" },
  { value: "Hottub", pack: "base" },
  { value: "Fire Pit", pack: "base" },
  { value: "Livestock", pack: "Cottage Living" },
  { value: "swingset", pack: "base" },
  { value: "shed", pack: "base" },
  { value: "monkey bars", pack: "base" },
  { value: "garage", pack: "base" },
  { value: "water feature", pack: "base" },
  { value: "chimney", pack: "base" },
  { value: "Get Wet (Splash pad, sprinklers, waterballoons)", pack: "base" },
  { value: "Crafting Space (juices, Candles)", pack: "Eco Lifestyle" },
  { value: "Picinic Area", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
];

export const interiorFeatures = [
  { value: "Light Switches", pack: "base" },
  { value: "Pet door", pack: "Cats & Dogs" },
  { value: "mother in law door", pack: "base" },
  { value: "window planter boxes", pack: "base" },
  { value: "fireplace", pack: "base" },
  { value: "built in shelving", pack: "base" },
  { value: "carpeted bedrooms", pack: "base" },
  { value: "radiators", pack: "Snowy Escape" },
  { value: "ceiling fans", pack: "base" },
  { value: "thermostats", pack: "Seasons" },
  { value: "overhead lighting", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
];

export const extraRoom = [
  { value: "Storage room", pack: "base" },
  { value: "basement", pack: "base" },
  { value: "attic", pack: "base" },
  { value: "gym", pack: "base" },
  { value: "art studio", pack: "base" },
  { value: "nursery", pack: "base" },
  { value: "game room", pack: "base" },
  { value: "guestroom", pack: "base" },
  { value: "crafting room", pack: "base" },
  { value: "greenhouse", pack: "base" },
  { value: "library", pack: "base" },
  { value: "laundry room", pack: "base" },
  { value: "meditation space", pack: "Spa Day" },
  { value: "Storage room", pack: "base" },
  { value: "work shop", pack: "base" },
  { value: "music room", pack: "base" },
  { value: "playroom", pack: "base" },
  { value: "office", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
  { value: "roll2", pack: "base" },
];

export const familyType = [
  { value: "Family", pack: "base" },
  { value: "Single Sim", pack: "base" },
  { value: "Couple", pack: "base" },
  { value: "Roommates", pack: "base" },
];

export const challenge = [
  { value: "Jail Cell", pack: "Get to Work" },
  { value: "toilet cult shrine", pack: "base" },
  { value: "cupcake machine", pack: "base" },
  { value: "make it grungy", pack: "base" },
  { value: "too many plants", pack: "base" },
  { value: "too much clutter", pack: "base" },
  { value: "messy sims", pack: "base" },
  { value: "cemetry/urns", pack: "base" },
  { value: "electricity is the devil", pack: "base" },
  { value: "tragic clown painting", pack: "base" },
  { value: "grogu arrives", pack: "base" },
  { value: "mooder gauntlet", pack: "base" },
  { value: "Suit of Armour", pack: "base" },
  { value: "open air bathroom", pack: "base" },
  { value: "chairs are toilets", pack: "base" },
  { value: "braking bad", pack: "base" },
  { value: "phone a friend", pack: "base" },
  { value: "leave it alone", pack: "base" },
  { value: "roll2", pack: "base" },
];
