export const expansionPackList = [
  { label: "Get to Work" },
  { label: "Get Together" },
  { label: "City Living" },
  { label: "Cats & Dogs" },
  { label: "Seasons" },
  { label: "Get Famous" },
  { label: "Island Living" },
  { label: "Discover University" },
  { label: "Eco Lifestyle" },
  { label: "Snowy Escape" },
  { label: "Cottage Living" },
  { label: "High School Years" },
  { label: "Growing Together" },
  { label: "Horse Ranch" },
  { label: "For Rent" },
];

export const gamePackList = [
  { label: "Outdoor Retreat" },
  { label: "Spa Day" },
  { label: "Dine Out" },
  { label: "Vampires" },
  { label: "Parenthood" },
  { label: "Jungle Adventure" },
  { label: "StrangerVille" },
  { label: "Realm of Magic" },
  { label: "Journey to Batuu" },
  { label: "Dream Home Decorator" },
  { label: "My Wedding Stories" },
  { label: "Werewolves" },
];

export const stuffPackList = [
  { label: "Luxury Party" },
  { label: "Perfect Patio" },
  { label: "Cool Kitchen" },
  { label: "Spooky Stuff" },
  { label: "Movie Hangout" },
  { label: "Romantic Garden" },
  { label: "Kids Room" },
  { label: "Backyard" },
  { label: "Vintage Glamour" },
  { label: "Bowling Night" },
  { label: "Fitness" },
  { label: "Toddler" },
  { label: "Laundry Day" },
  { label: "My First Pet" },
  { label: "Moschino" },
  { label: "Tiny Living" },
  { label: "Nifty Knitting" },
  { label: "Paranormal" },
  { label: "Home Chef Hustle" },
];

export const kitsList = [
  { label: "Country Kitchen" },
  { label: "Bust the Dust" },
  { label: "Throwback Fit" },
  { label: "Courtyard Oasis" },
  { label: "Industrial Loft" },
  { label: "Fashion Street" },
  { label: "Incheon Arrivals" },
  { label: "Blooming Rooms" },
  { label: "Modern Menswear" },
  { label: "Carnaval Streetwear" },
  { label: "Décor to the Max" },
  { label: "Little Campers" },
  { label: "Moonlight Chic" },
  { label: "First Fits" },
  { label: "Desert Luxe" },
  { label: "Everyday Clutter" },
  { label: "Pastel Pop" },
  { label: "Bathroom Clutter" },
  { label: "Simtimates Collection" },
  { label: "Basement Treasures" },
  { label: "Greenhouse Haven" },
  { label: "Book Nook" },
  { label: "Grunge Revival" },
  { label: "Poolside Splash" },
  { label: "Modern Luxe" },
];

// Worlds (locations) by owning pack
export const worlds = [
  { value: "Willow Creek", pack: "base" },
  { value: "Oasis Springs", pack: "base" },
  { value: "Newcrest", pack: "base" },
  { value: "San Myshuno", pack: "City Living" },
  { value: "Brindleton Bay", pack: "Cats & Dogs" },
  { value: "Del Sol Valley", pack: "Get Famous" },
  { value: "Sulani", pack: "Island Living" },
  { value: "Britechester", pack: "Discover University" },
  { value: "Evergreen Harbor", pack: "Eco Lifestyle" },
  { value: "Mt. Komorebi", pack: "Snowy Escape" },
  { value: "Henford-on-Bagley", pack: "Cottage Living" },
  { value: "Copperdale", pack: "High School Years" },
  { value: "San Sequoia", pack: "Growing Together" },
  { value: "Chestnut Ridge", pack: "Horse Ranch" },
  { value: "Granite Falls", pack: "Outdoor Retreat" },
  { value: "Selvadorada", pack: "Jungle Adventure" },
  { value: "StrangerVille", pack: "StrangerVille" },
  { value: "Glimmerbrook", pack: "Realm of Magic" },
  { value: "Batuu", pack: "Journey to Batuu" },
  { value: "Tartosa", pack: "My Wedding Stories" },
  { value: "Moonwood Mill", pack: "Werewolves" },
];

// Lot constraints
export const lotSizes = [
  { value: "20x15", pack: "base" },
  { value: "20x20", pack: "base" },
  { value: "30x20", pack: "base" },
  { value: "30x30", pack: "base" },
  { value: "40x30", pack: "base" },
  { value: "40x40", pack: "base" },
  { value: "50x40", pack: "base" },
  { value: "50x50", pack: "base" },
  { value: "64x64", pack: "base" },
];

export const budgetTiers = [
  { value: "Starter (≤ §20,000)", pack: "base" },
  { value: "Modest (≤ §35,000)", pack: "base" },
  { value: "Comfortable (≤ §60,000)", pack: "base" },
  { value: "Luxury (≤ §100,000)", pack: "base" },
  { value: "Unlimited (no budget)", pack: "base" },
];

export const houseBuild = [
  { value: "Micro Home", pack: "base" },
  { value: "Tiny Home", pack: "base" },
  { value: "Small Home", pack: "base" },
  { value: "Regular Home", pack: "base" },
];

export const houseConcept = [
  { value: "Open Concept", pack: "base" },
  { value: "Closed Concept", pack: "base" },
];

export const houseStyle = [
  { value: "Cape Cod", pack: "base" },
  { value: "Contemporary", pack: "base" },
  { value: "Shotgun", pack: "base" },
  { value: "Midcentury", pack: "base" },
  { value: "Cottage", pack: "base" },
  { value: "Trailer", pack: "base" },
  { value: "Container", pack: "base" },
  { value: "Colonial", pack: "base" },
  { value: "Craftsman", pack: "base" },
  { value: "Ranch", pack: "base" },
  { value: "Art Deco", pack: "base" },
  { value: "Underground", pack: "base" },
  { value: "Bungalow", pack: "base" },
  { value: "Abandoned", pack: "base" },
  { value: "Rustic", pack: "base" },
  { value: "Farmhouse", pack: "base" },
  { value: "Suburban", pack: "base" },
  { value: "Dealers Choice", pack: "base" },
  { value: "roll2", pack: "base" },
];

export const houseExterior = [
  { value: "Brick", pack: "base" },
  { value: "Panelling", pack: "base" },
  { value: "Siding", pack: "base" },
  { value: "Shingles", pack: "base" },
  { value: "Metal", pack: "base" },
  { value: "Dealers Choice", pack: "base" },
  { value: "roll2", pack: "base" },
  { value: "roll3", pack: "base" },
];

export const exteriorColorScheme = [
  { value: "Boring Beige", pack: "base" },
  { value: "Neon", pack: "base" },
  { value: "Earthy", pack: "base" },
  { value: "Beachy", pack: "base" },
  { value: "Pastel", pack: "base" },
  { value: "Jewel Tones", pack: "base" },
  { value: "Monochromatic", pack: "base" },
  { value: "Primary Colors", pack: "base" },
  { value: "Neutral with pop of color", pack: "base" },
  { value: "Bold", pack: "base" },
  { value: "High Contrast", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
];

export const interiorColorScheme = [
  { value: "Boring Beige", pack: "base" },
  { value: "Neon", pack: "base" },
  { value: "Earthy", pack: "base" },
  { value: "Beachy", pack: "base" },
  { value: "Pastel", pack: "base" },
  { value: "Jewel Tones", pack: "base" },
  { value: "Monochromatic", pack: "base" },
  { value: "Primary Colors", pack: "base" },
  { value: "Neutral with pop of color", pack: "base" },
  { value: "Bold", pack: "base" },
  { value: "High Contrast", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
];

export const exteriorFeatures = [
  { value: "Pond", pack: "base" },
  { value: "Garden", pack: "base" },
  { value: "Pool", pack: "base" },
  { value: "Sandbox", pack: "base" },
  { value: "Patio", pack: "base" },
  { value: "Porch", pack: "base" },
  { value: "Driveway", pack: "base" },
  { value: "Hottub", pack: "base" },
  { value: "Fire Pit", pack: "base" },
  { value: "Livestock", pack: "Cottage Living" },
  { value: "swingset", pack: "base" },
  { value: "shed", pack: "base" },
  { value: "monkey bars", pack: "base" },
  { value: "garage", pack: "base" },
  { value: "water feature", pack: "base" },
  { value: "chimney", pack: "base" },
  { value: "Get Wet (Splash pad, sprinklers, waterballoons)", pack: "base" },
  { value: "Crafting Space (juices, Candles)", pack: "Eco Lifestyle" },
  { value: "Picinic Area", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
];

export const interiorFeatures = [
  { value: "Light Switches", pack: "base" },
  { value: "Pet door", pack: "Cats & Dogs" },
  { value: "mother in law door", pack: "base" },
  { value: "window planter boxes", pack: "base" },
  { value: "fireplace", pack: "base" },
  { value: "built in shelving", pack: "base" },
  { value: "carpeted bedrooms", pack: "base" },
  { value: "radiators", pack: "Snowy Escape" },
  { value: "ceiling fans", pack: "base" },
  { value: "thermostats", pack: "Seasons" },
  { value: "overhead lighting", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
];

export const extraRoom = [
  { value: "Storage room", pack: "base" },
  { value: "basement", pack: "base" },
  { value: "attic", pack: "base" },
  { value: "gym", pack: "base" },
  { value: "art studio", pack: "base" },
  { value: "nursery", pack: "base" },
  { value: "game room", pack: "base" },
  { value: "guestroom", pack: "base" },
  { value: "crafting room", pack: "base" },
  { value: "greenhouse", pack: "base" },
  { value: "library", pack: "base" },
  { value: "laundry room", pack: "base" },
  { value: "meditation space", pack: "Spa Day" },
  { value: "Storage room", pack: "base" },
  { value: "work shop", pack: "base" },
  { value: "music room", pack: "base" },
  { value: "playroom", pack: "base" },
  { value: "office", pack: "base" },
  { value: "Dealer's Choice", pack: "base" },
  { value: "roll2", pack: "base" },
];

export const familyType = [
  { value: "Family", pack: "base" },
  { value: "Single Sim", pack: "base" },
  { value: "Couple", pack: "base" },
  { value: "Roommates", pack: "base" },
];

export const challenge = [
  { value: "Jail Cell", pack: "Get to Work" },
  { value: "toilet cult shrine", pack: "base" },
  { value: "cupcake machine", pack: "base" },
  { value: "make it grungy", pack: "base" },
  { value: "too many plants", pack: "base" },
  { value: "too much clutter", pack: "base" },
  { value: "messy sims", pack: "base" },
  { value: "cemetry/urns", pack: "base" },
  { value: "electricity is the devil", pack: "base" },
  { value: "tragic clown painting", pack: "base" },
  { value: "grogu arrives", pack: "base" },
  { value: "mooder gauntlet", pack: "base" },
  { value: "Suit of Armour", pack: "base" },
  { value: "open air bathroom", pack: "base" },
  { value: "chairs are toilets", pack: "base" },
  { value: "braking bad", pack: "base" },
  { value: "phone a friend", pack: "base" },
  { value: "leave it alone", pack: "base" },
  { value: "roll2", pack: "base" },
];
